# Generated by Django 4.1.7 on 2023-04-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Қала аты')),
                ('text', models.CharField(blank=True, max_length=100, verbose_name='Текс')),
                ('img', models.CharField(blank=True, max_length=100, verbose_name='Суреті')),
            ],
        ),
    ]
