# Generated by Django 4.1.7 on 2023-04-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0003_citys_descriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Қала аты')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='Текс')),
                ('img', models.CharField(blank=True, max_length=300, verbose_name='Суреті')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='Бағасы')),
            ],
        ),
        migrations.AlterField(
            model_name='citys',
            name='descriptions',
            field=models.TextField(blank=True, default='text', verbose_name='Толық текст'),
        ),
    ]
