# Generated by Django 4.1.7 on 2023-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0005_hotel_city_alter_hotel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты-жөні')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Номер')),
                ('hotel', models.CharField(max_length=100, verbose_name='Қонақ үй')),
                ('child', models.IntegerField(verbose_name='Балалар саны')),
                ('adult', models.IntegerField(verbose_name='Ересек саны')),
                ('date1', models.DateField(verbose_name='Алу куны')),
                ('date2', models.DateField(verbose_name='Откізу күні')),
            ],
        ),
    ]
