# Generated by Django 4.1.7 on 2023-04-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0006_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_eur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бағасы евромен'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_rus',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бағасы рубльмен'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_usd',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бағасы доллармен'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='Бағасы теңгемен'),
        ),
    ]
