# Generated by Django 4.1.7 on 2023-04-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0007_hotel_price_eur_hotel_price_rus_hotel_price_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('text', models.CharField(max_length=100, verbose_name='Текс')),
                ('subject', models.CharField(max_length=100, verbose_name='Тақырыбы')),
            ],
        ),
    ]
