# Generated by Django 4.2 on 2023-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='citys',
            name='descriptions_1',
            field=models.TextField(blank=True, default='text', verbose_name='Тур текст'),
        ),
        migrations.AlterField(
            model_name='citys',
            name='img',
            field=models.CharField(blank=True, default='text', max_length=300, verbose_name='Суреті'),
        ),
    ]
