# Generated by Django 4.2 on 2023-06-01 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0012_requests_card_number_requests_cardholder_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Аты')),
            ],
            options={
                'verbose_name': 'Туробъекті',
                'verbose_name_plural': 'Туробъектілер',
            },
        ),
        migrations.AlterModelOptions(
            name='citys',
            options={'verbose_name': 'Қала', 'verbose_name_plural': 'Қалалар'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Қонақ үй', 'verbose_name_plural': 'Қонақ үйлер'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Хабарлама', 'verbose_name_plural': 'Хабарламалар'},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Сұраныс', 'verbose_name_plural': 'Сұраныстар'},
        ),
        migrations.CreateModel(
            name='ObjectsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Аты')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('map', models.CharField(max_length=150, verbose_name='Орналасқан жері')),
                ('tourobjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourizmapp.tourobjects', verbose_name='Туробъекті')),
            ],
            options={
                'verbose_name': 'Туробъекті туралы',
                'verbose_name_plural': 'Туробъектілер туралы',
            },
        ),
        migrations.CreateModel(
            name='ImageShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='imageshots/')),
                ('objectsdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourizmapp.objectsdetail')),
            ],
            options={
                'verbose_name': 'Сурет',
                'verbose_name_plural': 'Суреттер',
            },
        ),
    ]
