# Generated by Django 4.2 on 2023-06-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0013_tourobjects_alter_citys_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsdetail',
            name='image',
            field=models.ImageField(null=True, upload_to='imageshots/'),
        ),
    ]
