# Generated by Django 4.2 on 2023-06-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0014_objectsdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsdetail',
            name='map_in_google',
            field=models.TextField(null=True, verbose_name='Картада'),
        ),
        migrations.DeleteModel(
            name='ImageShots',
        ),
    ]
