# Generated by Django 4.2 on 2023-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0015_objectsdetail_map_in_google_delete_imageshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourobjects',
            name='image',
            field=models.ImageField(null=True, upload_to='imageshots/'),
        ),
    ]
