# Generated by Django 4.2 on 2023-06-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0016_tourobjects_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(max_length=150, verbose_name='Тегі')),
                ('city', models.CharField(max_length=150, verbose_name='Қала')),
                ('language', models.CharField(max_length=150, verbose_name='Тіл')),
                ('image', models.ImageField(upload_to='guides/')),
                ('experience', models.IntegerField(verbose_name='Тәжірибе')),
            ],
            options={
                'verbose_name': 'Гид',
                'verbose_name_plural': 'Гидтер',
            },
        ),
    ]
