# Generated by Django 4.2 on 2023-06-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0017_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='citys',
            name='descriptions_1_en',
            field=models.TextField(blank=True, default='text', verbose_name='Тур текст'),
        ),
        migrations.AddField(
            model_name='citys',
            name='descriptions_1_ru',
            field=models.TextField(blank=True, default='text', verbose_name='Тур текст'),
        ),
        migrations.AddField(
            model_name='citys',
            name='descriptions_en',
            field=models.TextField(blank=True, default='text', verbose_name='Толық текст'),
        ),
        migrations.AddField(
            model_name='citys',
            name='descriptions_ru',
            field=models.TextField(blank=True, default='text', verbose_name='Толық текст'),
        ),
        migrations.AddField(
            model_name='citys',
            name='text_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текс'),
        ),
        migrations.AddField(
            model_name='citys',
            name='text_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Текс'),
        ),
        migrations.AddField(
            model_name='objectsdetail',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Сипаттама'),
        ),
        migrations.AddField(
            model_name='objectsdetail',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Сипаттама'),
        ),
    ]
