# Generated by Django 4.2 on 2023-06-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourizmapp', '0018_citys_descriptions_1_en_citys_descriptions_1_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectsdetail',
            name='name_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Аты'),
        ),
        migrations.AddField(
            model_name='objectsdetail',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Аты'),
        ),
    ]
